#############################################################################
# Makefile for building: Simweather
# Generated by qmake (3.0) (Qt 5.1.1) on: ?? ???. 15 17:52:24 2013
# Project:  Simweather.pro
# Template: app
# Command: /home/gooddocteur/Programs/qt/5.1.1/gcc_64/bin/qmake -o Makefile Simweather.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_SENSORS_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Programs/qt/5.1.1/gcc_64/mkspecs/linux-g++ -I. -I. -I../../Programs/qt/5.1.1/gcc_64/include -I../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets -I../../Programs/qt/5.1.1/gcc_64/include/QtQuick -I../../Programs/qt/5.1.1/gcc_64/include/QtOpenGL -I../../Programs/qt/5.1.1/gcc_64/include/QtPrintSupport -I../../Programs/qt/5.1.1/gcc_64/include/QtWebKit -I../../Programs/qt/5.1.1/gcc_64/include/QtQml -I../../Programs/qt/5.1.1/gcc_64/include/QtWidgets -I../../Programs/qt/5.1.1/gcc_64/include/QtSensors -I../../Programs/qt/5.1.1/gcc_64/include/QtXml -I../../Programs/qt/5.1.1/gcc_64/include/QtNetwork -I../../Programs/qt/5.1.1/gcc_64/include/QtGui -I../../Programs/qt/5.1.1/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/gooddocteur/Programs/qt/5.1.1/gcc_64 -Wl,-rpath,/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib -Wl,-rpath-link,/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib -lQt5WebKitWidgets -lQt5Quick -lQt5OpenGL -lQt5PrintSupport -lQt5WebKit -lQt5Qml -lQt5Widgets -lQt5Sensors -lQt5Xml -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/gooddocteur/Programs/qt/5.1.1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		taker.cpp \
		formato.cpp \
		view.cpp qrc_res.cpp \
		moc_taker.cpp \
		moc_formato.cpp \
		moc_view.cpp
OBJECTS       = main.o \
		taker.o \
		formato.o \
		view.o \
		qrc_res.o \
		moc_taker.o \
		moc_formato.o \
		moc_view.o
DIST          = ../../Programs/qt/5.1.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/unix.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/linux.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/qconfig.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/default_post.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/qt.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/resources.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/moc.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/uic.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/yacc.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/lex.prf \
		Simweather.pro \
		res.qrc \
		Simweather.pro
QMAKE_TARGET  = Simweather
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Simweather


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Simweather.pro ../../Programs/qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../Programs/qt/5.1.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/unix.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/linux.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/qconfig.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/default_post.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/qt.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/resources.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/moc.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/uic.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/yacc.prf \
		../../Programs/qt/5.1.1/gcc_64/mkspecs/features/lex.prf \
		Simweather.pro \
		res.qrc \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5WebKitWidgets.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Quick.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5OpenGL.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5PrintSupport.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5WebKit.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Network.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Qml.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Widgets.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Sensors.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Xml.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Gui.prl \
		/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Simweather.pro
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/spec_pre.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/common/shell-unix.conf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/common/unix.conf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/common/linux.conf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/common/gcc-base.conf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/common/g++-base.conf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/common/g++-unix.conf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/qconfig.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_v8.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/qt_functions.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/qt_config.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/spec_post.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/default_pre.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/default_pre.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/resolve_config.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/default_post.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/warn_on.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/qt.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/resources.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/moc.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/uic.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/unix/thread.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/wayland-scanner.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/exceptions.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/yacc.prf:
../../Programs/qt/5.1.1/gcc_64/mkspecs/features/lex.prf:
Simweather.pro:
res.qrc:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5WebKitWidgets.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Quick.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5OpenGL.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5PrintSupport.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5WebKit.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Network.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Qml.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Widgets.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Sensors.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Xml.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Gui.prl:
/home/gooddocteur/Programs/qt/5.1.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Simweather.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Simweather1.0.0 || mkdir -p .tmp/Simweather1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Simweather1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/Simweather1.0.0/ && $(COPY_FILE) --parents taker.hpp formato.hpp view.hpp .tmp/Simweather1.0.0/ && $(COPY_FILE) --parents main.cpp taker.cpp formato.cpp view.cpp .tmp/Simweather1.0.0/ && (cd `dirname .tmp/Simweather1.0.0` && $(TAR) Simweather1.0.0.tar Simweather1.0.0 && $(COMPRESS) Simweather1.0.0.tar) && $(MOVE) `dirname .tmp/Simweather1.0.0`/Simweather1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Simweather1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		resources/no_data.html \
		resources/template.html
	/home/gooddocteur/Programs/qt/5.1.1/gcc_64/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_wayland_server_header_make_all:
compiler_wayland_server_header_clean:
compiler_wayland_client_header_make_all:
compiler_wayland_client_header_clean:
compiler_qtwayland_client_header_make_all:
compiler_qtwayland_client_header_clean:
compiler_qtwayland_server_header_make_all:
compiler_qtwayland_server_header_clean:
compiler_moc_header_make_all: moc_taker.cpp moc_formato.cpp moc_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_taker.cpp moc_formato.cpp moc_view.cpp
moc_taker.cpp: ../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QApplication \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qeventloop.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qguiapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qinputmethod.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QUrl \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/QNetworkReply \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QIODevice \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QString \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QVariant \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/QNetworkRequest \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QSharedDataPointer \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QObject \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/QDomDocument \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qdom.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qtxmlglobal.h \
		taker.hpp
	/home/gooddocteur/Programs/qt/5.1.1/gcc_64/bin/moc $(DEFINES) $(INCPATH) taker.hpp -o moc_taker.cpp

moc_formato.cpp: ../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QApplication \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qeventloop.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qguiapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qinputmethod.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/QDomDocument \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qdom.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qtxmlglobal.h \
		formato.hpp
	/home/gooddocteur/Programs/qt/5.1.1/gcc_64/bin/moc $(DEFINES) $(INCPATH) formato.hpp -o moc_formato.cpp

moc_view.cpp: ../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QMainWindow \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qicon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets/QWebView \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets/qwebview.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKit/qwebkitglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets/qwebpage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKit/qwebsettings.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainter.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtextoption.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpen.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QObject \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QLineEdit \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qlineedit.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qframe.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtextcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtextformat.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QPushButton \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QStackedWidget \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qstackedwidget.h \
		view.hpp
	/home/gooddocteur/Programs/qt/5.1.1/gcc_64/bin/moc $(DEFINES) $(INCPATH) view.hpp -o moc_view.cpp

compiler_wayland_code_make_all:
compiler_wayland_code_clean:
compiler_qtwayland_client_code_make_all:
compiler_qtwayland_client_code_clean:
compiler_qtwayland_server_code_make_all:
compiler_qtwayland_server_code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QApplication \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qeventloop.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qguiapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qinputmethod.h \
		taker.hpp \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QUrl \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/QNetworkReply \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QIODevice \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QString \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QVariant \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/QNetworkRequest \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QSharedDataPointer \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QObject \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/QDomDocument \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qdom.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qtxmlglobal.h \
		formato.hpp \
		view.hpp \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QMainWindow \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qicon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets/QWebView \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets/qwebview.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKit/qwebkitglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets/qwebpage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKit/qwebsettings.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainter.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtextoption.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpen.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QLineEdit \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qlineedit.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qframe.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtextcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtextformat.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QPushButton \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QStackedWidget \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qstackedwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

taker.o: taker.cpp ../../Programs/qt/5.1.1/gcc_64/include/QtCore/QDebug \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		taker.hpp \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QApplication \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qeventloop.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qguiapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qinputmethod.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QUrl \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/QNetworkReply \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QIODevice \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QString \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QVariant \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/QNetworkRequest \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QSharedDataPointer \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QObject \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/QDomDocument \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qdom.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qtxmlglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taker.o taker.cpp

formato.o: formato.cpp ../../Programs/qt/5.1.1/gcc_64/include/QtCore/QDebug \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QFile \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QDateTime \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdatetime.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		formato.hpp \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QApplication \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qeventloop.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qguiapplication.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qinputmethod.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/QDomDocument \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qdom.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtXml/qtxmlglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formato.o formato.cpp

view.o: view.cpp ../../Programs/qt/5.1.1/gcc_64/include/QtCore/QFile \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QTextStream \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QHBoxLayout \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qboxlayout.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qlayout.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qgridlayout.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QVBoxLayout \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QGraphicsOpacityEffect \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qgraphicseffect.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QPropertyAnimation \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qpropertyanimation.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qvariantanimation.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qeasingcurve.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/qabstractanimation.h \
		view.hpp \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QMainWindow \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qicon.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets/QWebView \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets/qwebview.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKit/qwebkitglobal.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKitWidgets/qwebpage.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWebKit/qwebsettings.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpainter.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtextoption.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qpen.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtCore/QObject \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QLineEdit \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qlineedit.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qframe.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtextcursor.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtGui/qtextformat.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QPushButton \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/QStackedWidget \
		../../Programs/qt/5.1.1/gcc_64/include/QtWidgets/qstackedwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o view.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_taker.o: moc_taker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taker.o moc_taker.cpp

moc_formato.o: moc_formato.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formato.o moc_formato.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

