######################################################################
# Automatically generated by qmake (3.0) ?? ???. 13 05:44:46 2013
######################################################################

TEMPLATE = app
TARGET = Simweather
INCLUDEPATH += .
QT += widgets
QT += network
QT += xml

# Input
HEADERS += taker.hpp
SOURCES += main.cpp taker.cpp
