######################################################################
# Automatically generated by qmake (3.0) ?? ???. 13 05:44:46 2013
######################################################################

TEMPLATE = app
TARGET = Simweather
INCLUDEPATH += .
RESOURCES += res.qrc

QMAKE_CXXFLAGS += -std=c++11
QT += widgets
QT += network
QT += xml

# Input
HEADERS += taker.hpp formato.hpp
SOURCES += main.cpp taker.cpp formato.cpp
